# Generated by Django 5.2.4 on 2025-07-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipients',
            new_name='Recipient',
        ),
    ]
